graph TD
    switch_s1[switch:s1]
    host_h1[host:h1]
    host_h2[host:h2]
    host_h3[host:h3]
    iface_s1_eth1[iface:s1-eth1]
    iface_s1_eth2[iface:s1-eth2]
    iface_s1_eth3[iface:s1-eth3]
    switch_s1_unknown_s1_eth1[switch:s1:unknown:s1-eth1]
    switch_s1_unknown_s1_eth2[switch:s1:unknown:s1-eth2]
    switch_s1_unknown_s1_eth3[switch:s1:unknown:s1-eth3]
    path_s1_>h1[path:s1->h1]
    path_s1_>h2[path:s1->h2]
    path_s1_>h3[path:s1->h3]
    switch_s1 -->|link| host_h1
    switch_s1 -->|link| host_h2
    switch_s1 -->|link| host_h3
    switch_s1 -->|has_interface| iface_s1_eth1
    switch_s1 -->|has_interface| iface_s1_eth2
    switch_s1 -->|has_interface| iface_s1_eth3
    switch_s1 -->|has_port| switch_s1_unknown_s1_eth1
    switch_s1_unknown_s1_eth1 -->|maps_interface| iface_s1_eth1
    switch_s1 -->|has_port| switch_s1_unknown_s1_eth2
    switch_s1_unknown_s1_eth2 -->|maps_interface| iface_s1_eth2
    switch_s1 -->|has_port| switch_s1_unknown_s1_eth3
    switch_s1_unknown_s1_eth3 -->|maps_interface| iface_s1_eth3
    switch_s1 -->|path_source| path_s1_>h1
    path_s1_>h1 -->|path_target| host_h1
    switch_s1_unknown_s1_eth1 -->|path_port| path_s1_>h1
    switch_s1 -->|path_source| path_s1_>h2
    path_s1_>h2 -->|path_target| host_h2
    switch_s1_unknown_s1_eth2 -->|path_port| path_s1_>h2
    switch_s1 -->|path_source| path_s1_>h3
    path_s1_>h3 -->|path_target| host_h3
    switch_s1_unknown_s1_eth3 -->|path_port| path_s1_>h3
