apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nsddos-default
spec:
  podSelector:
    matchLabels:
      app: nsddos
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
  egress:
    - to: []
